export const CHALLENGE_ROOM_REPOSIT0RY = 'CHALLENGE_ROOM_REPOSIT0RY';
export const CHALLENGE_REPOSITORY = 'CHALLENGE_REPOSITORY';
export const CHALLENGE_QUEUE_CONFIG_TOKEN = 'CHALLENGE_QUEUE_CONFIG';
export const CHALLENGE_CONFIG_TOKEN = 'CHALLENGE_CONFIG';
